# Generated by Django 5.0.2 on 2024-02-29 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("group", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="group",
            name="students",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
